server:
  port: ${PORT:${SERVER_PORT:0}}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

info:
  id: ${spring.application.name}

agende:
  pubsub:
    topic:
      profissional:
        listener: hom-profissional
        subscribe: hom-profissional-subscribe
      agendamento:
        listener: hom-agendamento
        subscribe: hom-agendamento-subscribe
        publish: hom-agendamento-to-web
      usuario:
        listener: hom-paciente
        subscribe: hom-paciente-subscribe
        publish: hom-paciente-to-web
        
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    serviceUrl:      
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true      

feign:
  hystrix:
    enabled: true
  compression:
    min-request-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    request:
      enabled: true
    response:
      enabled: true
  httpclient:
    enabled: true    
  client:
    config:
      feignName:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: full
        decode404: false
#        errorDecoder: com.example.SimpleErrorDecoder
#        retryer: com.example.SimpleRetryer
#        requestInterceptors:
#        - com.example.FooRequestInterceptor
#        - com.example.BarRequestInterceptor
#        encoder: com.example.SimpleEncoder
#        decoder: com.example.SimpleDecoder
#        contract: com.example.SimpleContract
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 300000          
ribbon:
  ConnectTimeout:  10000
  ReadTimeout:  10000 
---
spring:
  profiles: producao
  zipkin:
    baseUrl: http://zipkin-service:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
agende:
  pubsub:
    topic:
      profissional:
        listener: profissional
        subscribe: profissional-subscribe
      agendamento:
        listener: agendamento
        subscribe: agendamento-subscribe
        publish: agendamento-to-web
      usuario:
        listener: paciente
        subscribe: paciente-subscribe
        publish: paciente-to-web      
#logging:
#  level: warn
#  logstash:
#    host: logstash
